# Generated by Django 4.1.1 on 2022-09-22 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='洲别名称')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='国家代码')),
                ('cn_name', models.CharField(max_length=200, verbose_name='国家中文名称')),
                ('en_name', models.CharField(max_length=200, verbose_name='国家英文名称')),
                ('cn_abbr', models.CharField(max_length=50, verbose_name='国家中文简称')),
                ('en_abbr', models.CharField(max_length=100, verbose_name='国家英文简称')),
                ('domain', models.CharField(max_length=5, unique=True, verbose_name='域名')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crms.continent', verbose_name='所属洲别')),
            ],
        ),
        migrations.CreateModel(
            name='TelAreaCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='国际电话区号')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crms.country', verbose_name='所属国家')),
            ],
        ),
    ]
