# Generated by Django 4.1.1 on 2022-09-23 12:45

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='国家')),
            ],
        ),
    ]
