# Generated by Django 4.1.1 on 2022-09-23 15:42

from django.db import migrations, models
import django.db.models.deletion
import tools.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=32, verbose_name='产品分类')),
                ('cate_desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='产品分类说明')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cate_P', to='products.category', verbose_name='父类')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRelative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('product_photo', models.ImageField(blank=True, upload_to='upload/products/', validators=[tools.validators.validate_file_size], verbose_name='产品图片')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='产品类别')),
            ],
        ),
    ]
