# Generated by Django 4.1.1 on 2022-09-23 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cate_desc',
            field=models.CharField(blank=True, default='无', max_length=200, null=True, verbose_name='产品分类说明'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, default='无', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cate_P', to='products.category', verbose_name='父类'),
        ),
    ]
